id: eae426624f2747388516d45aeeb79e32
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_85-The_Question_of_Maitreya-v1
  language: bo
  author: ''
  volume: {}
